[package]
name = "kompact"
version = "0.4.0"
authors = ["Lars Kroll <lkroll@kth.se>", "Johan Mickos <johanmi@kth.se>"]

description = "Kompact is a Rust implementation of the Kompics component model combined with the Actor model."

# documentation = "..."
homepage = "http://kompics.sics.se"
repository = "https://github.com/kompics/kompact"
readme = "../README.md"
keywords = ["actor", "kompics", "component", "async"]
categories = ["asynchronous", "concurrency", "network-programming"]
license = "MIT"

[badges]
# Maintenance: `status` is required Available options are `actively-developed`,
# `passively-maintained`, `as-is`, `none`, `experimental`, `looking-for-maintainer`
# and `deprecated`.
maintenance = { status = "actively-developed" }

[features]
default = ["serde","slog/max_level_debug", "slog/release_max_level_info"]

[dependencies]
log = "0.3"
kompact-component-derive = { version="0.4.0", path = "../macros/component-definition-derive/" }
kompact-actor-derive = { version="0.4.0", path = "../macros/actor-derive/" }
executors = "0.4"
crossbeam = "0.3"
crossbeam-channel = "0.2"
synchronoise = "0.4"
uuid = { version = "0.4", features = ["v4"] }
time = "0.1"
as_num = "0.2"
num_cpus = "1.0"
oncemutex = "0.1.1"
sequence_trie = "0.3.5"
slog = {version = "2.2"}
slog-async = "2.3"
slog-term = "2.4"

# Optional
protobuf = {version = "2", optional = true, features = ["with-bytes"]}
serde = {version = "1.0", optional = true}

# Network-specific
bytes = "0.4.8"
futures = "0.1.2"
tokio = "0.1.7"
tokio-retry = "0.2.0"
spaniel = "0.1"
bitfields = "0.1"

[dependencies.petty]
path = "../../petty"

#[dependencies.spaniel]
#git = "https://github.com/jarlopez/spaniel"
#branch = "master"

#[dependencies.bitfields]
#git = "https://github.com/jarlopez/bitfields-rs"
#branch = "master"


[dev-dependencies]
#env_logger = "0.4"
